### ISSUE TITLE
m3u8资源 下载一部分片段后 .会生成proxy.m3u8

### ISSUE THREAD

**Issue by tmphuang6** [JeffMony/PlayerSDK#3]
然后我去用这个proxy.m3u8去播放..但是当本地下载好的片段播完后 就不会继续播放了,就是停在网络片段那里 .我看代码 会走下面这段

    // We can't seek inside the buffer, and so need to reset.
    pendingResetPositionUs = positionUs;
    loadingFinished = false;
    mediaChunks.clear();
    if (loader.isLoading()) {
      if (sampleQueuesBuilt) {
        // Discard as much as we can synchronously.
        for (SampleQueue sampleQueue : sampleQueues) {
          sampleQueue.discardToEnd();
        }
      }
      loader.cancelLoading();

**Comment by tmphuang6** [comment]
假设某个ts片段有问题. 播放失败 会继续吗?

**Comment by JeffMony** [comment]
不好意思，没太听明白你的问题？
你是下载好了文件播放失败还是没有下载好的文件播放失败？

**Comment by tmphuang6** [comment]
下载好的文件 播放 失败.. 下载一半的时候也试过会失败
